### ISSUE TITLE
MacOS X support

### ISSUE THREAD

**Issue by jesperpedersen** [agroal/pgagroal#325]
Identified as

```
System is Darwin
```

**Comment by 2010YOUY01** [comment]
I'm trying to make it run on OSX, it can build so far, but there are several issues:
1. ld linker on OSX doesn't seem to have '-z' option, it will throw errors `ld: unknown option: -z
clang: error: linker command failed with exit code 1 (use -v to see invocation)`, so those lines to set the option are disabled https://github.com/agroal/pgagroal/blob/master/src/CMakeLists.txt#L142 I'm not sure if it will cause any problem.
2. How can I perform something like an integration test to make sure everything works?

**Comment by jesperpedersen** [comment]
1) Hmm, checks like https://github.com/agroal/pgagroal/blob/master/src/CMakeLists.txt#L202 should catch this, and disable the linker flag. Any idea of why it fails ?

2) Unfortunately, it is a manual setup - you can follow the tutorials in order to get a basic setup - https://github.com/agroal/pgagroal/tree/master/doc/tutorial

Thanks for working on this !

**Comment by 2010YOUY01** [comment]
> 1. Hmm, checks like https://github.com/agroal/pgagroal/blob/master/src/CMakeLists.txt#L202 should catch this, and disable the linker flag. Any idea of why it fails ?
> 2. Unfortunately, it is a manual setup - you can follow the tutorials in order to get a basic setup - https://github.com/agroal/pgagroal/tree/master/doc/tutorial
> 
> Thanks for working on this !

Cool! I will setup and test it later.

For 1. according to the compiler manual
> /usr/bin/clang --help | grep "\-Wl"
  -Wl,<arg>               Pass the comma separated arguments in <arg> to the linker
> /usr/bin/clang --help | grep "\-z "
  -z <arg>                Pass -z <arg> to the linker

`-Wl` and `-z` options in the compiler seem only forward it to the linker, and it didn't care if the linker supports that. (same for gcc)
The doc for linker on Linux said it support `-z` option, and OSX doesn't.

So both on Linux and OSX, https://github.com/agroal/pgagroal/blob/master/src/CMakeLists.txt#L202 `HAS_RELRO` is set.
I tried changing it to `check_linker_flag("-z relro" HAS_RELRO)`. On Linux it's set, on OSX it's not set, which is the expected behavior.
If that's the case, this issue can be fixed first.

**Comment by jesperpedersen** [comment]
Sounds good - feel free to send pull requests once you have them; remember to add yourself to the `AUTHORS` file.

Thanks !

**Comment by jesperpedersen** [comment]
Maybe the initial patch should be a dedicated `Darwin` branch based on the `Linux` one...

**Comment by 2010YOUY01** [comment]
So all the changes for Darwin support should be done in a new branch, could you help create a `Darwin` branch then I can send PRs to that branch?

**Comment by jesperpedersen** [comment]
I meant a `CMakeFiles.txt` branch -- aka `elseif (${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")`

**Comment by jesperpedersen** [comment]
This is done - thanks @2010YOUY01 !
